//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.Web.WCFServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/Sat.Web.Services")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceReference.ITestWCF")]
    public interface ITestWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestWCF/DoWork", ReplyAction="http://tempuri.org/ITestWCF/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestWCF/DoWork", ReplyAction="http://tempuri.org/ITestWCF/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestWCF/Sumar", ReplyAction="http://tempuri.org/ITestWCF/SumarResponse")]
        int Sumar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestWCF/Sumar", ReplyAction="http://tempuri.org/ITestWCF/SumarResponse")]
        System.Threading.Tasks.Task<int> SumarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestWCF/RetornarPersona", ReplyAction="http://tempuri.org/ITestWCF/RetornarPersonaResponse")]
        Sat.Web.WCFServiceReference.Persona RetornarPersona();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestWCF/RetornarPersona", ReplyAction="http://tempuri.org/ITestWCF/RetornarPersonaResponse")]
        System.Threading.Tasks.Task<Sat.Web.WCFServiceReference.Persona> RetornarPersonaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestWCFChannel : Sat.Web.WCFServiceReference.ITestWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestWCFClient : System.ServiceModel.ClientBase<Sat.Web.WCFServiceReference.ITestWCF>, Sat.Web.WCFServiceReference.ITestWCF {
        
        public TestWCFClient() {
        }
        
        public TestWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public int Sumar() {
            return base.Channel.Sumar();
        }
        
        public System.Threading.Tasks.Task<int> SumarAsync() {
            return base.Channel.SumarAsync();
        }
        
        public Sat.Web.WCFServiceReference.Persona RetornarPersona() {
            return base.Channel.RetornarPersona();
        }
        
        public System.Threading.Tasks.Task<Sat.Web.WCFServiceReference.Persona> RetornarPersonaAsync() {
            return base.Channel.RetornarPersonaAsync();
        }
    }
}
