//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public Empleados()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public decimal cod_emp { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string cedula { get; set; }
        public int Activo { get; set; }
        public string Cargo { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<decimal> cod_edificio { get; set; }
        public string Edificio { get; set; }
        public Nullable<decimal> piso { get; set; }
        public string cod_ubic { get; set; }
        public string cod_carg { get; set; }
        public string e_mail { get; set; }
    
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
