//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public long IdSolicitud { get; set; }
        public Nullable<decimal> Cod_emp { get; set; }
        public string Solicitud1 { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string HoraCreacion { get; set; }
        public Nullable<decimal> IdResponsable { get; set; }
        public Nullable<decimal> IdTecnico { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public string HoraAsignacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<long> Cod_Equipo { get; set; }
        public Nullable<System.DateTime> FechaElaborado { get; set; }
        public string HolaElaborado { get; set; }
        public string Evaluacion1 { get; set; }
        public string Evaluacion2 { get; set; }
        public string Evaluacion3 { get; set; }
        public Nullable<System.DateTime> FechaEvaluacion { get; set; }
        public string HoraEvaluacion { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
