//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Rol = new HashSet<Rol>();
        }
    
        public int IDUsuario { get; set; }
        public string Usuario1 { get; set; }
        public string Clave { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> UltimoCambioClave { get; set; }
        public Nullable<System.DateTime> FechaUltimoError { get; set; }
        public int ErroresAcceso { get; set; }
    
        public virtual ICollection<Rol> Rol { get; set; }
    }
}
